steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'src/'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'microservice-function', '--trigger-topic', 'microservice-metadata', '--runtime', 'nodejs10']
  dir: 'src/'
